const UPDATE_TITLE = "UPDATE_TITLE"
const UPDATE_DESCRIPTION = "UPDATE_DESCRIPTION"
const UPDATE_EXPRESSION = "UPDATE_EXPRESSION"
const EVAL_EXPRESSION = "EVAL_EXPRESSION"

const UPDATE_VARIABLE_NAME = "UPDATE_VARIABLE_NAME"
const UPDATE_VARIABLE_VALUE = "UPDATE_VARIABLE_VALUE"
const ADD_VARIABLE = "ADD_VARIABLE"

const UPDATE_CONSTANT_VALUE = "UPDATE_CONSTANT_VALUE"
const UPDATE_CONSTANT_NAME = "UPDATE_CONSTANT_NAME"
const UPDATE_CONSTANT_DEFAULT = "UPDATE_CONSTANT_DEFAULT"
const ADD_CONSTANT = "ADD_CONSTANT"

const UPDATE_CONDITION_EXPRESSION = "UPDATE_CONDITION_EXPRESSION"
const UPDATE_CONDITION_STATEMENT = "UPDATE_CONDITION_STATEMENT"

const RESOLVE_CONSTANT_VALUE = "RESOLVE_CONSTANT_VALUE"
const RESOLVE_ALL_CONSTANT_VALUE = "RESOLVE_ALL_CONSTANT_VALUE"


export { 
  UPDATE_TITLE,
  UPDATE_DESCRIPTION,
  UPDATE_EXPRESSION,
  EVAL_EXPRESSION,
  ADD_VARIABLE,
  UPDATE_VARIABLE_NAME,
  UPDATE_VARIABLE_VALUE,
  UPDATE_CONSTANT_VALUE,
  UPDATE_CONSTANT_NAME,
  UPDATE_CONSTANT_DEFAULT,
  ADD_CONSTANT,
  UPDATE_CONDITION_EXPRESSION,
  UPDATE_CONDITION_STATEMENT,
  RESOLVE_CONSTANT_VALUE,
  RESOLVE_ALL_CONSTANT_VALUE
} 