const ADD_ARTICLE = "ADD_ARTICLE"
const UPDATE_TITLE = "UPDATE_TITLE"
const UPDATE_DESCRIPTION = "UPDATE_DESCRIPTION"
const UPDATE_EXPRESSION = "UPDATE_EXPRESSION"
const EVAL_EXPRESSION = "EVAL_EXPRESSION"

export { 
  ADD_ARTICLE,
  UPDATE_TITLE,
  UPDATE_DESCRIPTION,
  UPDATE_EXPRESSION,
  EVAL_EXPRESSION
} 